### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by ph1ex0n** [v-florinskiy/exmo-exchange-trade-bot#1]
что бы это могло значить?
~/bots/exmo>node index.js
/root/bots/exmo/index.js:16
let currentPair = currency1+'_'+currency2;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by ph1ex0n** [comment]
пардон, нода старая, можно закрыть
